### ISSUE TITLE
Composer installation

### ISSUE THREAD

**Issue by alexbaat** [mollie/Shopware6#10]
According to the docs you should place the plugin in custom/plugins and then run composer install within MolliePayments directory. This will create a new vendor directory within your custom/plugin directory. Because it also requires shopware/* it filles up this new vendor directory with shopware again and all their dependencies. 
Can't you place the plugin on packagist so I can just require it and it will be placed within my projects vendor directory?
I've now included it within in my composer.json with vcs and a link to github to avoid this but then I have to delete/change the autoload link in the MolliePayments.php

**Comment by galois-mf** [comment]
Yes, please build it composer and Shopware 6 compatible. A Shopware 6 installation has a central vendor folder where the composer packages belong. This package is only a plugin and is never installed standalone.
If you use henrikvolmer's pull-request [#2](https://github.com/mollie/Shopware6/pull/3), it works reliably and you do not build a parallel structure to the vendor folder of the Shopware 6 installation in the plugin's folder.
Please test your plugin with shopware6/development.There it will work without the need of a separate autoload, because then it will be installed in the vendor folder of the Shopware 6 installation.  This will also work if you do it via the admin frontend.
Then the mollie api package will also be found correctly by autoloading the Shopware 6 installation.
[Issue 2](https://github.com/mollie/Shopware6/issues/2) and [Issue 10](https://github.com/mollie/Shopware6/issues/10) both refer to exactly this problem.
Please fix it, because otherwise you - in our case - exclude 500 companies that want to use mollie as payment service provider. Otherwise we will have to recommend another payment service provider to the companies.

**Comment by reindernl** [comment]
I will take this with me for the next update, thanks!

**Comment by peter-bztrs** [comment]
Just my 2 cents and maybe not fitting the original question, but if you place the plugin within the `custom/static-plugins` directory and run a `composer update` it will be included into the main Shopware composer flow.

**Comment by henrikvolmer** [comment]
Hey @reindernl,

unfortunately since the latest update the integration via Composer is not possible again...

Why was this line added again?

https://github.com/mollie/Shopware6/blob/6da22f75e3698276b7284234d605a0dfa3af43ef/src/MolliePayments.php#L5

Please remove again if possible

**Comment by reindernl** [comment]
@henrikvolmer I'm sorry, it was a bad merge. Removed again.
