### ISSUE TITLE
parameter expected to be string but given null - apikey seems to be null

### ISSUE THREAD

**Issue by KobusPost** [mollie/Shopware6#14]
Going live, but mollie plugin is giving me headaches.
When completing the order, I get an error on the frontend. The following error shows up in the logs:
php.CRITICAL: Uncaught Error: strtolower() expects parameter 1 to be string, null given {"exception":"[object] (TypeError(code: 0): strtolower() expects parameter 1 to be string, null given at /sw6/vendor/store.shopware.com/molliepayments/src/Handler/PaymentHandler.php:426)"} []

Seems to have something to do with the api keys. Got a related error on my dev setup, but that was solved by entering the apikey for each saleschannel individual. 
apikeys do exist in the database.
shopware 6.1.5 - mollie 1.0.7

**Comment by henrikvolmer** [comment]
Duplicates #13 

There is also a workaround for this bug .

**Comment by KobusPost** [comment]
I suspect it to be something different. Got the same setup in my dev env, where everything is working (as long as I configure the keys for every individual saleschannel. In my production env this is not working.

What is the workaround?

**Comment by KobusPost** [comment]
Oke, did a little bit of debugging and it seems that the paymenthandler can not find the APP_ENV environment variable. It is set.

**Comment by pascaljosephy** [comment]
We had the same problem. It turns out that our production server did not populate the $_ENV variable, because it is not recommended:

https://stackoverflow.com/questions/3780866/why-is-my-env-empty/27077452#27077452

We patched the plugin and removed the `strtolower($_ENV['APP_ENV']) === 'prod'` snippet. We hope that future versions contain this patch.

**Comment by reindernl** [comment]
Since version 1.0.8 we work with the environment variable of Shopware. It's injected through the dependency injection. This doesn't always work as expected unfortunately. So we're thinking of turning things around. The only reason we use that environment is to enable testing of payments on local environments, as Mollie doesn't allow to pass a webhook URL of a local domain and breaks the payment process. A solution is in the making.
