### ISSUE TITLE
Payment with Coupon not working

### ISSUE THREAD

**Issue by Ph0xEn** [mollie/Shopware6#171]
Hello,

since version 1.5.1 all payments with vouchers fail. The following error appears in the log:

`Product for id not found.`

Thank you for your help.

**Comment by MelvinAchterhuis** [comment]
We are encountering the same issue. Following error is thrown in the log:

`app.ERROR: An error occurred during processing the payment {"orderTransactionId":"6e21686f03cb48099ac23b307b8d4e71","exceptionMessage":"Could not create a Mollie payment url due to the following error: Product for id  not found."} []`

**Comment by schmitzcarsten** [comment]
I'm on it

**Comment by schmitzcarsten** [comment]
solved in v1.5.2
