### ISSUE TITLE
Loading ApplePay Direct and ApplePayPaymentMethod scripts all the time

### ISSUE THREAD

**Issue by wexollm** [mollie/Shopware6#195]
in the storefront/scr/main.js you load both ApplePayDirect and ApplePayPaymentMethod scripts all the time, they are not hooked into any data-attribute or class/id etc..  This means that the scripts are loaded all the time even though you do not have the applepay activated at all. I haven't looked in-depth where exactly the issue comes from the 2 scripts, but I do not see the point of loading something if it's not gonna be used. 

Furthermore, the main issue is when you add a promotion code in the cart then it disappears once you go to the Checkout page. If you decide to reload the page then an alert is popping up with information that you are about to lose some data before you have submitted the form and all this is coming from one of the scripts mentioned above.

My request is to load the scripts only when they are needed and this could be easily done by loading a specific data-attribute if apple pay is activated

**Comment by boxblinkracer** [comment]
Hi

thank you for your issue

that is all already fixed and about to be released soon.
Apple Pay has been completely refactored, and also the JS parts got improved step by step

the traditional apple pay is now only loaded in the checkout and account-payments
and the reason to load apple pay direct all the time is that it can be displayed in many spots, such as PDP, Listing, and future areas.
but the code has been improved, so that additional xhr requests are only done if a button has even been found :)
so it would be initialized, but it does nothing. this can of course also be done and even further improved in many ways, but due to other big changes this is the approach for now.

also the part with the missing promotion code is already fixed, i think you might have an additional sales channel,
the call was however accidentally done without a slug for it (so just the domain) which really is weird but it leads to that error due to some resets of the cart with a mixed sales channel context....

i hope this helps you

**Comment by boxblinkracer** [comment]
hi there
the new version with those changes have been released today in v1.5.4

**Comment by wexollm** [comment]
@boxblinkracer 
Awesome, Thanks :)

**Comment by boxblinkracer** [comment]
happy to help
I would now close this issue

feel free to contact us again if you have questions :)
