### ISSUE TITLE
Multiple voucher-types can be used for a single product.

### ISSUE THREAD

**Issue by sdobbelaere** [mollie/Shopware6#267]
Hi All
In plugin version 1.5.8 (since 1.5.5) one can set a voucher on the product-page.  
There are currently 3 options:
- ECO
- MEAL
- GIFT

However, our client just pointed out that their products qualify for both ECO and GIFT.
In the current version, one can only select 1 option.  This field should be a multi-select.

**Comment by boxblinkracer** [comment]
Hi
thank you for this
I would contact Mollie
because in the Mollie API its only possible to add 1 voucher type for a line item.
I think either it is not possible on their side (if I'm not completely wrong) or it doesnt make a difference

thanks for letting us know

**Comment by boxblinkracer** [comment]
Hi @sdobbelaere 

so I've talked to Mollie.
technically it's not possible to assign multiple categories to a product within the Mollie API itself (and probably not really necessary).
so technically spoken on the side of the plugin, if a category is provided in a line item, that basically "just" unlocks the voucher methods (if even allowed for the merchant within Mollie).

I was told that the merchant might knows best what type of category fits best for the product...also because he/she has agreements with voucher suppliers.
Unfortunately I don't know (and was not informed) about any downsides or things that could be affected in that case (and I don't think there are some).

If you still have questions, could you reach out to your Mollie partner account, who is more on the business than the technical side. 

So for now there's nothing I can do, and probably there's also no need for it :)

I hope this helps you

**Comment by sdobbelaere** [comment]
Hi @boxblinkracer 

Thank you for following up on this.  If I understand you correctly, any one of the Eco/Gift/Meal will work as long as the voucher is unlocked?  Interesting.  I'll have a look if someone can try that out on our side.

**Comment by boxblinkracer** [comment]
hi @sdobbelaere 

yes, so the logic that is affected (if any logic exists) then it could be that the Mollie payment page might show/hide different voucher suppliers...but thats out of scope from the plugin side, and I didnt get an answer on that (thats what I meant earlier).

the plugin just makes sure that voucher is only visible, if the conditions for starting such a checkout are met (meaning at least 1 line item in the cart with a configured category of these 3 types).

**Comment by sdobbelaere** [comment]
Understood. Thank you for the clarification.
