### ISSUE TITLE
Service Unavailable after upgrading to v6.4.9 and activating mollie

### ISSUE THREAD

**Issue by AchillesAlama** [mollie/Shopware6#316]
Hey, 

so yeah I decided to upgrade shopware from v6.4.7 to v6.4.9
steps I took
deactivated all plugins
upgrade
activate plugins (I did this step one by one, and when I get to Mollie the whole site goes down, backend and frontend)

![image](https://user-images.githubusercontent.com/50458892/158374955-5cd29aac-8129-48a2-9a1d-3545e435e940.png)

this is the message that I get on all requests etc 
one thing to note is that there is no logs 
am I the only one with this problem ?

**Comment by boxblinkracer** [comment]
Hi

thank you for this, this is a known thing
the release 6.4.9.0 has been released yesterday.
this means we usually make sure that we build the new shopware version and add it to our testing pipeline until we know if this works.
in most cases it should work without problems, unfortuantely the latest version has internal breaking changes which leads to this problem. we did already fix it today with this PR
https://github.com/mollie/Shopware6/pull/315

it will come with the next release. i dont have a day because we are still testing and investigating, but expect it to be (of course) as fast as possible.

so theres no support for 6.4.9.0 with the latest official release.
in general, i would always recommend to first test such upgrades on a testing system, and at least wait a few days before updating shopware, and not on the release date immeditely (because we also get it there).

i hope the PR helps you, it looks good so far,
we're doing our best

**Comment by AchillesAlama** [comment]
yeah i found this out on my test system. 
the live version is still on the older version and working. 

alright sounds great, thank you very much, i'll be waiting for the release. 

Cheers,

**Comment by boxblinkracer** [comment]
Hi

thank you very much for your feedback

I will open this issue again, so that others see it :)

**Comment by boxblinkracer** [comment]
Good morning.
The support for Shopware 6.4.9.0 has been added to the new release v2.1.2 which came out today in the Shopware Store.
Github release, tags and composer will follow later
