### ISSUE TITLE
Klarna Pay Later and Klarna Slice it - Payment status ?

### ISSUE THREAD

**Issue by wexollm** [mollie/Shopware6#331]
Hi, could you please explain something to me as I do not get it? 

Why do orders made with Klarna Pay Later and Klarna Slice it, have the state of Authorized where the payment is received from Klarna as soon as the order is placed, meaning that is Paid, as stated in Klarna documentation: 
"They settle their bill with Klarna within 30 days, with no interest to pay. They can even pay the invoice with one click. You’ll love it too, because you receive payment from Klarna immediately, without any credit or fraud risk."
     
Why the status is not automatically set as Paid, but Authorized?

**Comment by boxblinkracer** [comment]
Hi there
sure

when the customer buys something, he basically gives the money to klarna.
you as a merchant, do only get that money, once you confirm and notify klaran that the items are shipped.
then you get the money from klarna.

this means that a status is first authorized, and once its shipped, it will transfer to paid.

here is the full explanation that you might be looking for
https://github.com/mollie/Shopware6/wiki/Klarna-Pay-Later

**Comment by amin212121** [comment]
@boxblinkracer but the status from Authorized to Padi will be changed automatically in Shopware?

**Comment by boxblinkracer** [comment]
Hi
yes and no, depending on what you mean with the question :)

you need to trigger a shipment in Mollie. Mollie will then make sure to do everything that is required, so that Klarna will get the money to the merchant.
Then Mollie will send a webhook to Shopware with the new status "paid".
And in Shopware the plugin will automatically set the payment status to be "paid", and optionally (if order state mapping is used) also the order status to the one that is configured for "paid".

i hope this fully explains it
