### ISSUE TITLE
Support of headless setup

### ISSUE THREAD

**Issue by niklaswolf** [mollie/Shopware6#34]
Hi,
I found your guideline on using this plugin in a headless setup: https://github.com/mollie/Shopware6/wiki/Headless-setup-in-Shopware-6
But as I see it, this still requires a storefront saleschannel, because the event described in your guideline only get fired in the storefront controller (https://github.com/mollie/Shopware6/blob/737261b14bbb6f93fa809409c6fa4f6893f3db43/src/Storefront/Controller/PaymentController.php#L278).
So how do we use this without a storefront saleschannel?

**Comment by andreasemer** [comment]
@reindernl Are you already working in this topic, can you give us an update or a time estimation for it? 

We have seen, that Mollie is a offical payment method in Vuestorefront https://www.vuestorefront.io/technology-partners/payments

It's a very important topic for us and eveyone who is using Vuestorefront or every other headless system and want to use Mollie.

**Comment by milan-kiener** [comment]
We are working on a fix to support this. It should be released tomorrow.

**Comment by andreasemer** [comment]
Nice, thank you very much!

**Comment by milan-kiener** [comment]
@andreasemer We have added some extra error handling. Could you try out the new release? If you still experience trouble, please feel free to re-open the issue.

**Comment by niklaswolf** [comment]
@milan-kiener  unfortunately the update does not solve the problem.
As described in the issue description, the current PaymentController is bound to the storefront-scope
https://github.com/mollie/Shopware6/blob/affed7bd7ed8c99d77248f9cb8078092c4df981b/src/Storefront/Controller/PaymentController.php#L91

But this does not work in a headless setup, as there is no storefront saleschannel, only headless. The current implementation only works in headless-setups that have a additional storefront channel, which should not be the case!

**Comment by milan-kiener** [comment]
Hi Niklas, I've reopened the issue. We probably have to bind the payment controller to the api, but that will have some consequences, that's something we need to test. Alternative is to add an extra controller. We'll dive into this and keep you posted.

**Comment by AndreasA** [comment]
Another question: If I want to redirect the customer to a different redirect URL, there is currently no way as you only trigger the event but do not check for any possible changes or responses in the event. So therefore the default response will still be returned - at least without some hacks.

You could e.g. check if a redirect URL has been set/changed in the event and use that one instead. Or even check for a different response inside the event object as Symfony supports in several kernel event listeners.

**Comment by AndreasA** [comment]
Another issue is that the Payment-Return URLs, if the payment is started in headless are without the store prefix, e.g. if the store is at  `/de` as the URL is generated outside storefront.

It can be fixed by setting by setting the corresponding request attributes and use URLs of the current sales channel. However, this might actually be an issue with the headless pay route in Shopware currently.

**Comment by jlsjonas** [comment]
Perhaps the following repo could provide you with some more context (implementation of mollie in vue storefront, one of the main customer-facing uses of the headless setup) https://github.com/GetNoticedNL/vsf-payment-mollie-payments-api
While of course this links up towards vsf specifically (and for a magento2 backend) it should give a good indication on where to hook in to accomplish this.

**Comment by milan-kiener** [comment]
@niklaswolf We are aiming on adding a new controller for this. Because of the upcoming black friday there is a release stop after tomorrow, so we expect this issue to be resolved in a release after Black Friday. 

@jlsjonas We will take your documentation in consideration, thanks a lot :)

**Comment by jlsjonas** [comment]
@milan-kiener Is a production-worthy release this year still feasible given the current knowns? Otherwise, we'll have to look at a different payment provider or manual implementation (new website launch on sw6 + vsf is planned for end of year; everything is checked & on schedule apart from the mollie integration).

**Comment by milan-kiener** [comment]
@jlsjonas At this point we absolutely think it's feasible. This issue is one of our top priorities, I expect a production-worthy release in 3-4 wks.

**Comment by TitanNano** [comment]
@milan-kiener we also need this issue to be fixed as it blocks the release of our current project.

**Comment by niklaswolf** [comment]
@milan-kiener any news when the release will be available? :)

**Comment by milan-kiener** [comment]
@niklaswolf We decided to rewrite a part of the plugin to have a solid support for headless. We expect this to release in January. We will keep you posted on this.

**Comment by jlsjonas** [comment]
@milan-kiener That's... quite a setback, however it's better to have it properly implemented than to release something full of bugs ;)

**Comment by niklaswolf** [comment]
@milan-kiener any news?

**Comment by andreasemer** [comment]
@milan-kiener Can you please give us an update about this topic?

**Comment by jlsjonas** [comment]
It's the last working day of januari... I understand that schedules might shift a little but at least provide an update please? Businesses are relying on this...

**Comment by milan-kiener** [comment]
@jlsjonas @andreasemer This issue seems to concern two topics: support of Vue Storefront and support of headless in general. We've been able to do a successful setup with VSF and SW6, and tested the Mollie plugin successfully.

**Comment by niklaswolf** [comment]
@milan-kiener so you say it is possible to use the Mollie plugin just with a headless saleschannel? Because that's what the whole issue is about and I think you recognized the issue early on: 


> Hi Niklas, I've reopened the issue. We probably have to bind the payment controller to the api, but that will have some consequences, that's something we need to test. Alternative is to add an extra controller. We'll dive into this and keep you posted.



> @niklaswolf We are aiming on adding a new controller for this. Because of the upcoming black friday there is a release stop after tomorrow, so we expect this issue to be resolved in a release after Black Friday.



> @niklaswolf We decided to rewrite a part of the plugin to have a solid support for headless. We expect this to release in January. We will keep you posted on this.

**Comment by jlsjonas** [comment]
@milan-kiener (as addition to @niklaswolf's comment) unless something changed recently, that didn't work, as I had attempted that setup before stumbling on the issues mentioned in this ticket

**Comment by milan-kiener** [comment]
Hi @jlsjonas, it would be great if we could have a look together. Is there a way we can contact you directly? Please let me know.

**Comment by jlsjonas** [comment]
@milan-kiener Feel free to reach out on my twitter to exchange email/chat details (@jlsjonas)

**Comment by schmitzcarsten** [comment]
Hi all,

first of all, I take over this topic from kiener now. 

We got more informations form @niklaswolf today about the issue and are investigating this with high priority. 

If I have some new informations or a solution for you, I will post here about them

**Comment by schmitzcarsten** [comment]
@niklaswolf just a short information about the progress. Unfortunately it isn't as easy as I thought in the beginning. We have to create own routes for every custom payment route. This includes webhooks and normal payment flow. 

At the moment we are prototyping. When I have something that will fit the normal payment flow (success or failed PWA route), I will give you a branch where you may check, if it fits your needs. 

What I can say at the moment is

- you will have to activate headless for the saleschannel in plugin configuration
- we will only support the shopware payment flow (the configuration "Use standard failed payment redirect." will be ignored with headless)

I'm sorry that we can't give you a working version at the moment, but there is much more to do as thought.

**Comment by jlsjonas** [comment]
@schmitzcarsten which explains why the previous maintainer had postponed the work until after complete refactor that was expected end of 2020...
I guess that refactor never happened and we just got dragged along instead? We postponed our release for this issue...

**Comment by schmitzcarsten** [comment]
@jlsjonas I'm doing my very best to give you a solution soon. But at the moment I can't give you an ETA. Perhaps everything changes soon to a quick solution.
I do want to communicate the status today to update you all. It has the highest feature priority at the moment. 
I have it working now, that we track the correct payment status in complete headless environments. At the moment I'm working on the headless payment workflow. Webhooks will follow afterwards. 
A side note: we will add ngrok support for local development with this feature. That will give the possibility to test webhooks in local environments

**Comment by niklaswolf** [comment]
@schmitzcarsten  thanks for the update, much appreciated!

**Comment by andreasemer** [comment]
Thank you very much for the open communication @schmitzcarsten !

**Comment by AndreasA** [comment]
I am actually interested in how the final solution will be because I know that shopware6 itself already has issues with payment workflow in a strict headless environment as e.g. the finalize payment redirect URL is a storefront URL which then redirects to finish or error URL and from what I saw it cannot be overridden that easily (generated in a private method).

**Comment by schmitzcarsten** [comment]
@AndreasA yes, these are our problems too. The first step has been to create an own return store api route. There we are doing all the stuff of recognizing payment status and setting it correctly as shopware payment status. 
=> Payment status is set correctly at the moment.

- If an order is successful I'm redirecting the user to the /order route by giving the right orderId => leads user to a finish page
- If an order hasn't been successful, our shopware out of the box possibilities are low. What I need at the moment is an order failed route that allows to do a new payment (like the storefront has already). We have to create such a page on our own.

Webhooks will be a route like the return store api route. I think this won't be a problem at all.

If I have something that could be shown to the public, I will add a branch in github for you.

**Comment by jurriaanr** [comment]
We have been running into this problem since december 2019. Shopware has been aware of the problem since than as well, so I feel your pain Mollie. We are doing a nasty redirect hack in the storefront template, readding it on every mollie update. I still think the solution for having the event and allow any party to adjust the redirect url (and having all the necessary data for that in the event, like success/failure including code and message) and than picking up the redirect after that is the most straightforward solution. 

finalPayment -> set default storefront return url on event -> dispatch event -> use url from event for RedirectResponse

This will still not solve the problem of 'losing' the saleschannel along the way but since that is part of the order, if we get a reference to the order as well in the event at least some work is possible there. But yeah.. Shopwares headless promise has been a big joke sofar

**Comment by niklaswolf** [comment]
@schmitzcarsten any news about the progress? :)

**Comment by schmitzcarsten** [comment]
Nothing to really mention. We are working on a proof of concept for failed payments. I'm sry that I have no more news for you

**Comment by schmitzcarsten** [comment]
We got some questions about this topic outside of this thread. So that all get the updates here, just my notes here.

We are doing our best to provide a solution. But as you know shopware does not support complete headless setups, as some routes need the storefront. So we have to find a solution for complete headless support, but we are not considering it as a bug in the plugin. 

At the moment we are working on a solution to get a workflow for failed payments.

**Comment by MelvinAchterhuis** [comment]
So should be possible with 6.4.2.0? -> https://github.com/shopware/platform/blob/6.4.2.0/changelog/release-6-4-2-0/2021-05-31-allow-payment-without-storefront.md

**Comment by schmitzcarsten** [comment]
@MelvinAchterhuis We will have a close look to the new version soon.

**Comment by niklaswolf** [comment]
Any news here?
I see that the issue got the tag "On Roadmap", which looks promising :)

**Comment by boxblinkracer** [comment]
Hi Niklas

alright, so now that the main plugin itself gets more and more stable there will be some kind of "task force" to finally work on that feature.
We already had a kickoff, and they will work on that.
Sorry for the long delay :)

**Comment by 9heun9** [comment]
Hi Mollie, any news on this? This issue is very pressing ...  

For now: How can a workaround be established? It IS currently possible to use the Plugin from a custom storefront as long as the Shopware Storefront is used as well?  Even if it is for the sole purpose of redirecting back to the App? Can you confirm that this is possible? 

Thanks

**Comment by boxblinkracer** [comment]
Hi @9heun9 

so I've talked to Mollie, to see what I can respond in here.
Headless is being created, absoluteley, but due to the massive amount of features and plans we have for the Mollie plugin itself, it was not possible to also do this so far.

In the upper comment I've mentioned as "task force" that will do this.
so I have indeed good or at least "neutral" news on that, which I can say here.
That different team is about to start now / very soon.....I'm half-involved in here, so preparations have been done, and one of the next steps is to implement it.
So indeed sorry for being so late on that topic, but as you can hopefully see, really a lot is being done on the Mollie plugin in general in the meanwhile. 
The headless team are great guys and girls, and I think they will do a great job soon :)

**Comment by AndreasA** [comment]
In one project I definitely use mollie headless with Storefront enabled for the payment processing redirect routes. It mostly worked out of the box, except:

- Added an event listener (Symfony) to block all routes except the ones necessary for payment I need for payment for that sales channel.
- Created a route to manually change the payment method afterwards as it was necessary to be able to switch the payment method in the app which also allows switching to non mollie payments. Might not be necessary anymore, this was first done in a 6.3.3.x installation and the corresponding route was just kept during the update as it was working fine.

**Comment by boxblinkracer** [comment]
ah, nice one @AndreasA thanks, I'll pass that on immediately :)

**Comment by AndreasA** [comment]
Forgot to mention that we also had to replace the router service using a compiler pass originally as the wrong router service was used in some mollie plugin services (default Symfony instead of the storefront version). but that shouldn't be necessary anymore as now the correct router is used except at one place but that one is only relevant in case Mollie failed payment handling is used.

And optional but some routes have the parameter `storefrontUrl` which we automatically built correctly and added to the request using Symfony event listeners, so we did not need to send it from the app but that should be optional.

Furthermore, we set the corresponding URLs in to request attributes `SALES_CHANNEL_BASE_URL`, `SALES_CHANNEL_ABSOLUTE_BASE_URL`, `STOREFRONT_URL` so generated mails etc. used the correct URLs too but this might not be necessary anymore. As mentioned we started first with 6.3.3.x or even 6.3.2.x and Shopware itself still had more bugs in it regarding headless.

**Comment by 9heun9** [comment]
Thank You @AndreasA. Very useful indeed!

**Comment by pascalbayer** [comment]
Any plans or updates when this will be officially supported in the plug-in?

**Comment by boxblinkracer** [comment]
Hi @pascalbayer 
the team that does it did already create a concept...and they should soon start I think (i'm not directly involved).
besides that I'm about to step in, in addition to bring this to an end, sorry fro the long waiting time.

**Comment by pascalbayer** [comment]
Thanks @boxblinkracer. Any rough ETA? Will it be only a few more weeks or months? This is crucial for the decision on the payment provider we‘re going to use in our current project. Also is there a way we can support on getting that implemented sooner?

**Comment by boxblinkracer** [comment]
Hi
update on the headless so far:
* webhooks and payment routings are now moved to the API scope away from storefront dependencies
* iDEAL routes are done (for components)
* Credit Card routes are done (for components)
* Apple Pay Direct routes are done, only 1 step missing to finish the payment
* Payment Method data (Mollie Limits, etc..) is fully working for headless
* Cypress Tests exist
* Shopware Vue Storefront PWA does now fully work (except components which are developed in the meantime)

**Comment by TanjaBayer** [comment]
@boxblinkracer according to your last update webhook and payment methods should work now, (I assume with v2.2.2 of the plugin, or is this not correct?), we have it installed and completely removed the storefront sales channel, only a headless one is left.

However when setup the plugin and do a test run (tested on localhost and also a deployed staging system) we always get redirected to the <backend-url>/mollie/payment/{id} which results in an 500 because shopware is not able to resolve this url.

From the logs we see the plugin is able to find the correct (headless) saleschannel.

For me it sound like it is hitting this part: https://github.com/mollie/Shopware6/blob/master/src/Storefront/Controller/PaymentController.php#L107 which should not be the case without a storefront channel, right? Are we missing some important configuration out.

**Comment by boxblinkracer** [comment]
Hi
this is not released yet. thats why its not working
its only in my fork so far. if you want to give it a test run, maybe you can reach out in slack (shopware) and I'll give you some instructions? a merchant did already approve that its working for them :)

**Comment by karl-foerster** [comment]
@boxblinkracer I'm looking forward to see this updated/fixed as i'm struggling with the same issue like @TanjaBayer

**Comment by boxblinkracer** [comment]
@karl-foerster great, can you reach out to me.

at all:
now that subscriptions is finally released, the next big part is headless besides some smaller things that also need to be done :) 
for techies -> bit more fixing and testing, but also that huge rebasing, so you know what i'm talking about :D :D

**Comment by boxblinkracer** [comment]
hi all :)

I have good news
headless is already merged and available in the master branch.
next up is the QA process and soon our release :) 

thank you to all beta testers so far

**Comment by jlsjonas** [comment]
Congratulations! Sadly enough the project has long moved on, but at least it should be usable in the future :)

**Comment by boxblinkracer** [comment]
thank you,
yes, I'm sure someone will still need it :)

**Comment by boxblinkracer** [comment]
so
it's done :)
headless has finally been released with version 3.0

I will now celebrate closing this issue :)

feel free to add new issues (hopefully just feature requests *haha)
