### ISSUE TITLE
Feedback: minimum order value with in3 as payment method

### ISSUE THREAD

**Issue by MelvinAchterhuis** [mollie/Shopware6#379]
in3 has a minimum order value of 100 euro, otherwise Mollie will throw the following error:

`Error executing API call (422: Unprocessable Entity): The amount is lower than the minimum.`

This should be documented in the docs of the plugin, or there should be automatically a rule created that has a minimum cart value of 100 and assigned to in3

**Comment by boxblinkracer** [comment]
hi
thanks
this is a great idea,
at the moment we do not focus on building all these rules, because a merchant might already have rules that he needs to touch again instead of using a different prepared rule
and yes, I'm struggling a bit with rebuilding the documentation that mollie already has :D 
but you are totally right, that should be added to the plugin WIKI at least, thanks for this

**Comment by boxblinkracer** [comment]
added to the docs 
thx again
