### ISSUE TITLE
Wrong order status

### ISSUE THREAD

**Issue by amin212121** [mollie/Shopware6#403]
Hey in my case when Payment status === Authorised, order status must be Open but Mollie plugin didn't do it. (Looks like it happened first time)

Here is my Mollie plugins settings 
![image](https://user-images.githubusercontent.com/36712833/185049560-bc8cc475-92f6-4a1a-a6f5-e5f7128d35ee.png)

Here is Order statuses:
![image](https://user-images.githubusercontent.com/36712833/185049205-9748be37-873c-484b-9f90-9080b5b89d02.png)

Here is log from Mollie site 
![image](https://user-images.githubusercontent.com/36712833/185049655-7c13176a-827a-49fa-9c23-f4464a56c3db.png)

Mollie Version: 2.4.0

Message from Mollie.log: 

Webhook for order 16034 and Mollie ID: {SECURITY} has been received with Status: authorized (Session: ...) {"session":"","processors":{"uid":{"uid":"083413f"},"web":{"url":"/mollie/webhook/{SECURITY }","ip":"{SECURITY}","http_method":"POST","server":"{SECURITY}","referrer":null}}} []
--

 

<br class="Apple-interchange-newline">

Shopware log is empty

**Comment by boxblinkracer** [comment]
Hi @amin212121 

thanks for this

I wasn't able to reproduce it.
I've attached a screenshot of my test. Your screenshot has the order status "cancelled"...how did that happen?
because if i start a payment,, then fail (or cancel) and pay again with authorized and works as expected.

could you hover over the timestamp of the "cancelled". it will show you what system or user did this.
because due to the payment status, i doubt that mollie has anything to do with the cancellation ...otherwise it would look as on my screen.

<img width="1026" alt="11706___Orders___Shopware_Administration" src="https://user-images.githubusercontent.com/5579326/186183608-436d926b-f9ea-4fad-9aaf-75b0194de076.png">

**Comment by boxblinkracer** [comment]
oh and i think that the mollie process happened before the cancel...and because its already "open", it stays the same...which means that the feature might work and only the cancellation reason is what we are looking for
