### ISSUE TITLE
25 euro difference in refund manager for some orders

### ISSUE THREAD

**Issue by MelvinAchterhuis** [mollie/Shopware6#410]
Some orders have a 25 euro difference between total order amount and refundable amount:

![Screenshot 2022-08-26 at 13 00 57](https://user-images.githubusercontent.com/26538915/186889939-e7dae31a-794c-4ea2-a69e-d956e69e4383.png)

The data comes from the Mollie API, however I'm curious why this happens? :)

**Comment by boxblinkracer** [comment]
mollie allows to refund 25 EUR on top of the total amount for some payment methods...this can be used if a merchant wants to say "sorry" for instance :)
so that is just how it is with the Mollie API

here is the page to the api refs, where the totalAmount has a description on this
https://docs.mollie.com/reference/v2/refunds-api/create-payment-refund

i hope this helps :)

**Comment by MelvinAchterhuis** [comment]
Thanks. Makes sense now :)
