### ISSUE TITLE
Subscriptions: Webhook should not create a new order if transaction is not payed

### ISSUE THREAD

**Issue by michnhokn** [mollie/Shopware6#413]
If a renewal webhook is triggerd from mollie with a transaction id and the transcation is not payed, the order should not be created.

`src/Components/Subscription/SubscriptionManager.php`
![image](https://user-images.githubusercontent.com/38752255/187886166-85d61eff-92f1-482c-97b1-eca1dc741e6a.png)

In the future it might be better to track an already existing order an try to update just a payment.

**Comment by boxblinkracer** [comment]
Hi @michnhokn 

thanks for this
I think my colleague is already in contact with you, so that we can do a fix for this.

I'm basically open to this idea, the only problem is, that it would be on purpose to create an order.
because sometimes its good to have a legit order, which the customer would need to pay and fullfill within Shopware....

the problem you face, that mollie repeats the step because of a bug on their side that should not happen, would howerver be indeed solved with this :)

so what do you think of a plugin configuration like "allow to created failed renewal orders" YES/NO.
then a merchant can decide if its ok that customers should finish the payment because the orders should exist, or if failed payments shouldnt even be allowed to be created? 
if you like that feature, i think i can add it to the next release

also btw -> if you use that hotfix, please also add authorized and pending....if existing in the payment itself (dont know it by heart, but all 3 are positive states)

**Comment by michnhokn** [comment]
Hey @boxblinkracer,

You're right! 
I think such an config would be the best solution for now.

Thank you for the quick reply. I'm looking forward to the next release.

**Comment by boxblinkracer** [comment]
@michnhokn 
perfect, sounds good
I'll make sure we do it, shouldnt be a big change

**Comment by boxblinkracer** [comment]
already in the works ;)
https://github.com/mollie/Shopware6/pull/414
