### ISSUE TITLE
Mollie is not defined on checkout confirm page

### ISSUE THREAD

**Issue by maxout** [mollie/Shopware6#522]
I noticed that on the checkout confirm page it throws an error:
`
ReferenceError: Mollie is not defined`

the corresponding place in the code should be this one:

[https://github.com/mollie/Shopware6/blob/1c33680e003cba7686527f6b303a30cafbee9fdf/src/Resources/app/storefront/src/mollie-payments/plugins/creditcard-components-sw64.plugin.js#L44](https://github.com/mollie/Shopware6/blob/1c33680e003cba7686527f6b303a30cafbee9fdf/src/Resources/app/storefront/src/mollie-payments/plugins/creditcard-components-sw64.plugin.js#L44)

Here is Mollie used but not defined anywhere. 
Is this a known bug or do we have a local problem?

**Comment by boxblinkracer** [comment]
Hi there

this is because of the credit card components.
just double checked in Shopware default, so I don't get that problem.
but I know it from earlier support, it's in that case very likely due to a wrong custom theme or block inheritance

its the part here in the troubleshooting
https://github.com/mollie/Shopware6/wiki/Credit-Card

can you double check if the blocks in twig are correct. if you fix it, can you let me know, so I can improve the docs?

thank you :)

**Comment by maxout** [comment]
hey, thanks for the quick reply. components are enabled.
we use a customized theme. which blocks should i check?

**Comment by boxblinkracer** [comment]
Hi there

yes, perfect
thats the thing thats missing (Mollie.js)

so I guess you're happy and I can close this issue?

**Comment by maxout** [comment]
yes, i'm happy! i was looking for Mollie within the plugin. i didn't even think about it that there is an external script. 

thank you for the hint.
