### ISSUE TITLE
iDeal 

### ISSUE THREAD

**Issue by wexollm** [mollie/Shopware6#543]
Hey, could you please explain something to me :)

When a customer uses the iDeal payment method and chooses a Bank from the list, the customer chooses the bank this bank becomes a "preferred iDeal issuer" saved to the customer account, and if the customer wants to pay with iDeal and chooses another bank they can't. They always get redirected to the "preferred iDeal issuer".

It seems there is no way to make another selection of iDeal bank from the list once you have "preferred iDeal issuer"

Thanks in advance

**Comment by boxblinkracer** [comment]
Hi there

thank you for this.

oh thats interesting, I have to admin, there's no test case at the moment that inspects the switching itself, because with the sandbox we usually check if its used by either seeing an issuer selection on the mollie sandbox page, or immediately the payment page.

but the good thing is, I just did this case in another thing yesterday :)

so shouldnt be a problem, I'll check it out, make sure theres a test case for the future and fix it if I can reproduce it

thx for letting us know :)

**Comment by wexollm** [comment]
Hey @boxblinkracer 

Is there any new info about the issue, I described earlier?  Have you been able to reproduce it?

**Comment by boxblinkracer** [comment]
Hi
sorry for this late reply
but no, it works on my side
i start with a ING payment, then start a second one which leads to e.g. RABO 

also when the customer tries another payment, the same happens with the required dropdown selection...once its changed the preferred issuer is also changed. could it be that they dont change the preselected dropdown?

maybe the problem is that the preferred issuer is pre-selected which makes customers to forget to set it again?

**Comment by boxblinkracer** [comment]
Hi there
i wanted to ask if you have any updates on this?
