### ISSUE TITLE
Question: Which VAT calculation method is required by mollie?

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#56]
Hi again,

separate from the VAT issues in general with mollie. In Shopware 6 it is now possible to setup which VAT calculation method to use. If it should be calculated horizontally or vertically. 
I would like to know which one, I should use with mollie or does it support both?

Maybe changing this setting would actually fix the VAT calculation thing as e.g. vertical will calculate the VAT based on the last total.

**Comment by milan-kiener** [comment]
Hi AndreasA, the Mollie plugin should work in both scenarios. The only VAT issues that are known to us, are because of wrong VAT calculation in Shopware for discounts. Shopware is looking into this at the moment. In the meantime, we can provide a hotfix that fixes this on the plugin side (but that's not the way this should be solved). If you want, we can provide this hotfix.

**Comment by AndreasA** [comment]
@milan-kiener No, you are correct regarding tax calculation should be fixed with SW. I just wanted to know, if one of those two methods should be used or if it does't matter. It is not just discounts but in general summation of taxable amounts that is the issue I think.

As it doesn't matter. I am fine with it.
