### ISSUE TITLE
Plugin not compatible with shopware 6.5 (still using sw_csrf)

### ISSUE THREAD

**Issue by lchhieu** [mollie/Shopware6#632]
CSRF was removed for shopware 6.5. But this plugin still uses it.
I'm facing with the issue "Unknown "sw_csrf". 
Any suggestion for resolving this issue ?

Only facing with this issue on production mode (APP_ENV=prod)

**Comment by boxblinkracer** [comment]
Hi there

its indeed working for 6.5, and there are conditional statements that only include csrf in Shopware 6.4
because this plugin works for both 6.4 and 6.5

the only thing that we might have in here is that in a certain point with a specific configuration (such as prod) a twig page was forgotten, in that case i would need the page where you get this error

but as far as i know all parts where csrf are even tested in cypress in all shopware versions
and also we never heard any troubles about it, because that would lead to a major problem...so i guess it might be some kind of edge problem on a specific page....

the production mode is indeed interesting, i will double check it,
but could you still provide the page where you get this error please?

thanks

**Comment by boxblinkracer** [comment]
Hi

so it works in 6.5.5.2 and other versions for me, also in prod mode

the wishlist-widget.html.twig is not touched by the mollie plugin
are you sure that the problem is the plugin and not another plugin?

**Comment by boxblinkracer** [comment]
Hi
just wanted to ask if you have any updates on this :)

**Comment by dbMario** [comment]
Hi
We updated on SW6.5.7.3 and still same problem.
Error in Logs and in Dev-Mode.

`Can not render @Storefront/storefront/page/content/index.html.twig view: Unknown "sw_csrf" function. with these parameters: {"themeIconConfig":[],"mollie_csrf_available":false,"mollie_applepay_enabled":"xxxxxxxxxxxxx","mollie_javascript_use_shopware":0,"mollie_applepaydirect_enabled":false,"mollie_applepaydirect_restrictions":["plp","pdp"],"mollie_subscriptions_enabled":true}`
