### ISSUE TITLE
Refund-Manager not visible in Shopware 6.5

### ISSUE THREAD

**Issue by azngeek** [mollie/Shopware6#647]
It seems like, that the Refund-Manager is not visible in Shopware 6.5. We are currently setting it up in the development environment and double checked, that the refund manager is enabled. Also the admin storefront has been rebuilt. 

Are there any other settings which we could check?

![image](https://github.com/mollie/Shopware6/assets/213429/d99d721b-73fe-40dc-b9b9-6ab9096b6d72)

**Comment by boxblinkracer** [comment]
Hi there :)

in 6.5 it should be in a card above it
do you see this?

<img width="1084" alt="Screenshot 2023-10-27 at 08 18 13" src="https://github.com/mollie/Shopware6/assets/5579326/32658747-bc8a-467d-bdb0-fbe0584b0eae">

**Comment by niklaswolf** [comment]
I'll answer: I could swear that this was not visible when @azngeek created the issue :D 
But nevertheless the Button is always disabled... I don't see no clear indication, why this is the case, what are possible reasons? :)

**Comment by boxblinkracer** [comment]
hi there

buttons are not hidden but only disabled, to at least have some better knowledge on what exists
there is a check if shipping is possible, according to mollie, so if items are still left to be shipped
but there is also a side effect when the SwagCommercialPlugin is installed, then its always disabled.
this will be fixed in 1-2 weeks with the upcoming relase

**Comment by niklaswolf** [comment]
Ahh yep, the project has SwagCommercialPlugin installed. Fine, then we'll wait for the update, thanks :) 
I think you can close this issue

**Comment by boxblinkracer** [comment]
ok super, then it makes sense

perfect, we'll try to be fast :)
