### ISSUE TITLE
Could not create a Mollie Payment Url after PayPal declined payment

### ISSUE THREAD

**Issue by cybersec-dev** [mollie/Shopware6#65]
We had a customer trying to pay through PayPal, all of a sudden, PayPal blocked our Business-Account, but instead of giving the customer a error message according to what happened, it errored out in Symfony. 
Is this an issue on our end? Tell me if you need more informations about the version and what not.

Shopware v6.3.4.1 Stable Version
Mollie Plugin: 1.3.11

`Could not create a Mollie Payment Url, error: Could not create Mollie order, error: [2021-01-26T11:53:09+0000] Error executing API call (422: Unprocessable Entity): The payment method is not active in your website profile. Field: payment.method. Documentation: https://docs.mollie.com/reference/v2/orders-api/create-order`
![Bildschirmfoto 2021-01-26 um 13 07 41](https://user-images.githubusercontent.com/1422640/105843133-9063d080-5fd7-11eb-8192-63681177f8c0.png)

**Comment by schmitzcarsten** [comment]
First of all, you generally should turn off developer mode in a production environment. If you do, you would never see the symfony developer toolbar. 
In production mode these errors would have been catched by shopware and the customer would have gotten an error in the shop.
The error has been thrown, because the payment method isn't active any more. Deactivate paypal in backend and/or remove paypal from saleschannel
