### ISSUE TITLE
Automatic Cancellation does not change the order Status in Mollie

### ISSUE THREAD

**Issue by TanjaBayer** [mollie/Shopware6#656]
According to the wiki page the Automatic Cancellation should cancel payments in mollie when they are cancelled in shopware.

I tested both cancelling a payment and cancelling an order for Orders where the payment was still in the process 'Open'.

According to the mollie support there should be a way to cancel orders with a payment state in status 'Open'. However for me that was not yet successful.

The problem is that if a user leaves the paypal payment screen the payment will stay in the status 'Paid' (for 72h). This however is a  problem, as this keeps products from being sold.

Any Idea why the cancel is not working (the communication with mollie in general works fine)?
And any idea how to automatically cancle open paypal payments e.g. after 15 minutes?

**Comment by boxblinkracer** [comment]
Hi

thank you for your message

so only orders that are "authorized" "partially shipped" or "created" can be (automatically) cancelled in the Mollie API
this is the mollie status

if we are talking about paypal payments that are already "paid" then these cannot be cancelled
i would more transition the question into something else in here

why is a paypal payment "paid" if a user leaves the payment screen. then it should actually become expired.
can you double check those payments with the mollie dashboard, because that is the 100% truth.
if its paid in there, then it was paid.

also its very important to differentiate between the mollie status and the status in shopware. so if its "paid" in shopware while its not paid in mollie, then a flow builder action might interfer (the plugin shouldnt have a bug in that part)

i hope this helps :)

**Comment by boxblinkracer** [comment]
Hi

aaa, ok now it makes sense
so the 72 hours expiration time is just too long

the problem here is, that i cannot do anything in this case
thats the way how mollie itself works (if you scroll down here you see expiration times: https://docs.mollie.com/payments/status-changes)

so what would need to be done is a custom code that makes sure to "expire" things after a while.
i thought about adding it to the plugin, but i think we really need to stick to the mollie times in that case (also for debugging),
so you would need to create a custom cronjob or scheduled task, that verifies paypal orders that are open and have a creation time of xyz diff to datetime.now, and then just transition these

is that an option you could go with?

**Comment by TanjaBayer** [comment]
yes I think that might be an option. the only question which remains there and so far I did not find a answer somewhere... how long is the checkout link usable (we do not want to expire an order which the user is still able to pay when he has the mollie checkout page open)

**Comment by boxblinkracer** [comment]
Hi
yeah that is always a very interesting and complex thing unfortunately.
so the basic orders in mollie have a default expiration of 28 days (https://docs.mollie.com/orders/status-changes)
this however can be also adjusted using the plugin configuration

on top of this, as you already know now, is that payment methods or the attempted transactions have individual expirations which is a different thing

i hope this helps :)

**Comment by TanjaBayer** [comment]
Yeah I do not mean the order or payment expiration I mean the expiration of the Checkout Page link. In the Order you will find the following entry:

![order info](https://github.com/mollie/Shopware6/assets/30770185/f9506d6c-548c-4f42-b908-b7b87bfb5cc7)

However we noticed this was leading to an expired page after some time, but I do not know how long it takes until this page expires?

**Comment by BlackScorp** [comment]
@TanjaBayer this checkout URL have different lifetimes depending on payment method. Credit Card or Paypal for example have only 15 Minutes while Banktransfer has up to 100 days and Klarna 28 days. 

So it is not recommended to use this link, rather redirecting to order overview of the customer. here he has a red button "Complete order", at this point a "fresh" checkout url is generated from mollie API. So he can complete the order.

i hope this helps, iam going to close this ticket now
