### ISSUE TITLE
Checkout exception - Could not create a Mollie Payment Url

### ISSUE THREAD

**Issue by ghost** [mollie/Shopware6#66]
Plugin version: 1.3.11

Customers have been complaining that they are unable to pay their order, when proceeding to the payment the webshop throws an error and notifies the customer that the payment failed.

`[2021-01-25 14:32:46] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Could not create a Mollie Payment Url, error: Could not create Mollie order, error: [2021-01-25T14:32:46+0000] Error executing API call (422: Unprocessable Entity): Order line 1 is invalid. VAT amount is off. Expected VAT amount to be €30.29 (€174.50 × (21.00% / 121.00%)), got €30.28. Field: lines.1.vatAmount. Documentation: https://docs.mollie.com/guides/handling-errors" at /XXX/custom/plugins/MolliePayments/src/Handler/PaymentHandler.php line 246 {"exception":"[object] (RuntimeException(code: 0): Could not create a Mollie Payment Url, error: Could not create Mollie order, error: [2021-01-25T14:32:46+0000] Error executing API call (422: Unprocessable Entity): Order line 1 is invalid. VAT amount is off. Expected VAT amount to be €30.29 (€174.50 × (21.00% / 121.00%)), got €30.28. Field: lines.1.vatAmount. Documentation: https://docs.mollie.com/guides/handling-errors at /XXX/custom/plugins/MolliePayments/src/Handler/PaymentHandler.php:246)"} []`

**Comment by schmitzcarsten** [comment]
Hi, this is a known issue at the moment. 
Unfortunately the shopware tax calculation and the mollie tax calculation aren't exactly the same. Both tax calculation approaches are in the view of tax authority right. 
Due to not exactely same rounding in the algorithm, in edge cases this could lead to different calculated tax amounts (1 cent). 
At the moment this leads to an error and therefore the payment fails. 
We are preparing a fix for this at the moment.

**Comment by schmitzcarsten** [comment]
@ghost the issue will be fixed in version 1.3.12, planned release date is next Monday

**Comment by schmitzcarsten** [comment]
1.3.12 released. This fixes the described problem
