### ISSUE TITLE
Missing snippets for component error messages

### ISSUE THREAD

**Issue by runelaenen** [mollie/Shopware6#695]
When the Mollie Cart component has an error, it is shown in Dutch, even when the language of the component is French. There are no snippets for this available in the plugin.

<img width="450" alt="Screenshot 2024-01-16 at 14 10 21" src="https://github.com/mollie/Shopware6/assets/3930922/23cb2da0-a6e9-4171-a7ea-2ee416ba139b">

**Comment by BlackScorp** [comment]
hi @runelaenen 

those error messages are coming from mollie api when you submit the form. in order to handle the language we send the language code from the saleschannel to the api. for this the language iso codes require specific format.

mollie api allow as language code fr_FR but the default language code in shopware are fr-FR so we replace "-" with "_" and convert fr-FR to fr_FR.

so if you iso code is different and mollie does not recognize it, the messages are shown in dutch then.

can you check your locale iso of the saleschannel?

Best Regards

**Comment by BlackScorp** [comment]
@runelaenen iam closing the issue now, if you still have a problem, please reply
