### ISSUE TITLE
Discount in cart = broken checkout

### ISSUE THREAD

**Issue by DSDigitalSolution** [mollie/Shopware6#895]
We use Shopware's discount function for graduated prices. From a certain number of products, x% discount is granted. The discount is allocated to the shopping cart using the shopping cart rule. The discount expands the shopping cart by another “discount” item. From here the checkout no longer works; it only continues when the coupon is removed. The discount function is a standard Shopware feature.

![image](https://github.com/user-attachments/assets/a705a57a-edcc-4ea5-ac61-10c66047151a)

**Comment by BlackScorp** [comment]
HI @DSDigitalSolution we do test this case automatically with % and absolute values. Do you have some Error Logs.

i prepared an example rule

![image](https://github.com/user-attachments/assets/a2665f89-1934-4e93-af28-5ca449484bfc)

then i created a 50% promotion based on that rule

![image](https://github.com/user-attachments/assets/06a8c254-a25e-49b3-a138-1dcc271338cf)

and the checkout worked fine.

you can test it out on our showcase server https://sw6.mollie-shopware.rocks/ just add some products to cart until you have more than 100 euro value. the test mode is enabled.

i assume either you have an old plugin version where there might be a bug or something special was added to the code, maybe a 3rd party plugin cause the issue. or my example is not the same as yours.

we need to have some logs to understand what the problem here is

**Comment by BlackScorp** [comment]
@DSDigitalSolution is there still an issue or can i close the ticket?
